# $ brew install ansible
# $ ansible-playbook install.yml
# $ ansible-playbook -i inventory install.yml
- name: Install stuff
  hosts: localhost
  become: false
  vars:
    Brew_packages: 
      - asciidoctor
      - zsh
      - httpie
      - colima
      - ddev
      - ddgr
      - jq
      - diff-so-fancy
      - eza
      - fzf
      - git
      - go
      - lazygit
      - zsh
      - ripgrep
      - neovim
      - zoxide
      - thefuck
      - pipx
      - tmux
      - tree-sitter
      - tldr
    install_homebrew_if_missing: false
  pre_tasks:
      - name: Ensuring Homebrew Is Installed
        stat:
          path: /opt/homebrew/bin/brew
        register: homebrew_check

      - name: Fail If Homebrew Is Not Installed and install_homebrew_if_missing Is False
        fail:
          msg: Homebrew is missing, install from http://brew.sh
        when:
          - not homebrew_check.stat.exists
          - not install_homebrew_if_missing

      - name: Installing Homebrew
        shell: /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
        when:
          - not homebrew_check.stat.exists
          - install_homebrew_if_missing
  tasks:
    - name: Install zsh
      homebrew:
        name: zsh
        state: present
    - name: Change shell
      shell: chsh -s /bin/zsh
    - name: Install Asciidoctor
      homebrew:
        name: asciidoctor
        state: present
    - name: Install HTTPie
      homebrew:
        name: homebrew/cask/httpie
        state: present
    - name: Install Diff-So-fancy
      homebrew:
        name: diff-so-fancy
        state: present
    - name: Install EZA
      homebrew:
        name: eza
        state: present
    - name: Install zoxide
      homebrew:
        name: zoxide
        state: present
    - name: Install LazyGit
      homebrew:
        name: lazygit
        state: present
    - name: Install Golang
      homebrew:
        name: go
        state: present
    - name: Install Golang
      homebrew:
        name: tldr
        state: present
